#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC3043,SC1091,SC2155,SC3020,SC3010,SC2016

source /etc/init.d/functions-qosmate/gaming_device_ip
source /etc/init.d/functions-qosmate/speedtest_run

auto_setup() {
    echo "Starting qosmate auto-setup..."

    # Stop qosmate if it's running
    if /etc/init.d/qosmate status > /dev/null; then
        echo "Stopping qosmate for accurate speed test results..."
        /etc/init.d/qosmate stop
        sleep 5  # Give some time for the network to stabilize
    fi

    # Detect WAN interface
    WAN_INTERFACE=$(ifstatus wan | grep -e '"device"' | cut -d'"' -f4)
    L3_DEVICE=$(ifstatus wan | grep -e '"l3_device"' | cut -d'"' -f4)
    
    if [ -z "$WAN_INTERFACE" ] && [ -z "$L3_DEVICE" ]; then
        echo "Error: Unable to detect WAN interface. Please set it manually in the configuration."
        return 1
    fi

    FINAL_INTERFACE=${L3_DEVICE:-$WAN_INTERFACE}
    echo "Detected WAN interface: $FINAL_INTERFACE"

    sed -i "/option WAN/c\    option WAN '$FINAL_INTERFACE'" /etc/config/qosmate

    if [ $? -ne 0 ]; then
        echo "Error: Failed to update WAN interface in configuration. Please check the file /etc/config/qosmate"
        return 1
    fi

    echo "Do you want to run a speed test or enter speeds manually? [test/manual]"
    read -r speed_choice

    if [[ "$speed_choice" =~ ^[Mm]anual$ ]]; then
        echo "Please enter your download speed in Mbit/s:"
        read -r DOWNLOAD_SPEED
        echo "Please enter your upload speed in Mbit/s:"
        read -r UPLOAD_SPEED
    else
        speedtest_check_space
        speedtest_run
    fi

    echo "Speed test results:"
    echo "Download speed: $DOWNLOAD_SPEED Mbit/s"
    echo "Upload speed: $UPLOAD_SPEED Mbit/s"

    speed_convert
    gaming_device_ip
}
